version: "3.7"

services:
  app:
    build: .
    container_name: payment_gateway_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/payments?sslmode=disable
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=payments
      - DB_HOST=postgres
      - DB_PORT=5432
    command: ["/app/main"]
    networks:
      - app_network

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=payments
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres-volume:
